// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "tabulate_types.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// tabulate_table
table_t tabulate_table();
RcppExport SEXP _tabulate_tabulate_table() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(tabulate_table());
    return rcpp_result_gen;
END_RCPP
}
// table_add_row
void table_add_row(table_t table, row_t row);
RcppExport SEXP _tabulate_table_add_row(SEXP tableSEXP, SEXP rowSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< table_t >::type table(tableSEXP);
    Rcpp::traits::input_parameter< row_t >::type row(rowSEXP);
    table_add_row(table, row);
    return R_NilValue;
END_RCPP
}
// table_column
column_t table_column(table_t table, size_t index);
RcppExport SEXP _tabulate_table_column(SEXP tableSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< table_t >::type table(tableSEXP);
    Rcpp::traits::input_parameter< size_t >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(table_column(table, index));
    return rcpp_result_gen;
END_RCPP
}
// column_format
column_format_t column_format(column_t column);
RcppExport SEXP _tabulate_column_format(SEXP columnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< column_t >::type column(columnSEXP);
    rcpp_result_gen = Rcpp::wrap(column_format(column));
    return rcpp_result_gen;
END_RCPP
}
// column_format_font_align
void column_format_font_align(column_format_t column, font_align_t font_align);
RcppExport SEXP _tabulate_column_format_font_align(SEXP columnSEXP, SEXP font_alignSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< column_format_t >::type column(columnSEXP);
    Rcpp::traits::input_parameter< font_align_t >::type font_align(font_alignSEXP);
    column_format_font_align(column, font_align);
    return R_NilValue;
END_RCPP
}
// column_format_font_color
void column_format_font_color(column_format_t column, color_t color);
RcppExport SEXP _tabulate_column_format_font_color(SEXP columnSEXP, SEXP colorSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< column_format_t >::type column(columnSEXP);
    Rcpp::traits::input_parameter< color_t >::type color(colorSEXP);
    column_format_font_color(column, color);
    return R_NilValue;
END_RCPP
}
// tabulate_format
std::string tabulate_format(table_t table, bool colors);
RcppExport SEXP _tabulate_tabulate_format(SEXP tableSEXP, SEXP colorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< table_t >::type table(tableSEXP);
    Rcpp::traits::input_parameter< bool >::type colors(colorsSEXP);
    rcpp_result_gen = Rcpp::wrap(tabulate_format(table, colors));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tabulate_tabulate_table", (DL_FUNC) &_tabulate_tabulate_table, 0},
    {"_tabulate_table_add_row", (DL_FUNC) &_tabulate_table_add_row, 2},
    {"_tabulate_table_column", (DL_FUNC) &_tabulate_table_column, 2},
    {"_tabulate_column_format", (DL_FUNC) &_tabulate_column_format, 1},
    {"_tabulate_column_format_font_align", (DL_FUNC) &_tabulate_column_format_font_align, 2},
    {"_tabulate_column_format_font_color", (DL_FUNC) &_tabulate_column_format_font_color, 2},
    {"_tabulate_tabulate_format", (DL_FUNC) &_tabulate_tabulate_format, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_tabulate(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
