# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cell_set_text <- function(cell, text) {
    invisible(.Call(`_tabulate_cell_set_text`, cell, text))
}

cell_get_text <- function(cell) {
    .Call(`_tabulate_cell_get_text`, cell)
}

cell_format <- function(cell) {
    .Call(`_tabulate_cell_format`, cell)
}

column_format <- function(column) {
    .Call(`_tabulate_column_format`, column)
}

column_format_width <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_width`, column, value))
}

column_format_height <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_height`, column, value))
}

column_format_padding <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_padding`, column, value))
}

column_format_padding_left <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_padding_left`, column, value))
}

column_format_padding_right <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_padding_right`, column, value))
}

column_format_padding_top <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_padding_top`, column, value))
}

column_format_padding_bottom <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_padding_bottom`, column, value))
}

column_format_border <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border`, column, value))
}

column_format_border_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_color`, column, value))
}

column_format_border_background_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_background_color`, column, value))
}

column_format_border_left <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_left`, column, value))
}

column_format_border_left_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_left_color`, column, value))
}

column_format_border_left_background_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_left_background_color`, column, value))
}

column_format_border_right <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_right`, column, value))
}

column_format_border_right_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_right_color`, column, value))
}

column_format_border_right_background_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_right_background_color`, column, value))
}

column_format_border_top <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_top`, column, value))
}

column_format_border_top_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_top_color`, column, value))
}

column_format_border_top_background_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_top_background_color`, column, value))
}

column_format_border_bottom <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_bottom`, column, value))
}

column_format_border_bottom_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_bottom_color`, column, value))
}

column_format_border_bottom_background_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_bottom_background_color`, column, value))
}

column_format_corner <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_corner`, column, value))
}

column_format_corner_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_corner_color`, column, value))
}

column_format_corner_background_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_corner_background_color`, column, value))
}

column_format_column_separator <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_column_separator`, column, value))
}

column_format_column_separator_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_column_separator_color`, column, value))
}

column_format_column_separator_background_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_column_separator_background_color`, column, value))
}

column_format_font_align <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_font_align`, column, value))
}

column_format_font_style <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_font_style`, column, value))
}

column_format_font_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_font_color`, column, value))
}

column_format_font_background_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_font_background_color`, column, value))
}

column_format_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_color`, column, value))
}

column_format_background_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_background_color`, column, value))
}

column_format_multi_byte_characters <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_multi_byte_characters`, column, value))
}

column_format_locale <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_locale`, column, value))
}

c_format_width <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_width`, format, value))
}

c_format_height <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_height`, format, value))
}

c_format_padding <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_padding`, format, value))
}

c_format_padding_left <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_padding_left`, format, value))
}

c_format_padding_right <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_padding_right`, format, value))
}

c_format_padding_top <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_padding_top`, format, value))
}

c_format_padding_bottom <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_padding_bottom`, format, value))
}

c_format_border <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_border`, format, value))
}

c_format_border_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_border_color`, format, value))
}

c_format_border_background_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_border_background_color`, format, value))
}

c_format_border_left <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_border_left`, format, value))
}

c_format_border_left_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_border_left_color`, format, value))
}

c_format_border_left_background_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_border_left_background_color`, format, value))
}

c_format_border_right <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_border_right`, format, value))
}

c_format_border_right_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_border_right_color`, format, value))
}

c_format_border_right_background_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_border_right_background_color`, format, value))
}

c_format_border_top <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_border_top`, format, value))
}

c_format_border_top_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_border_top_color`, format, value))
}

c_format_border_top_background_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_border_top_background_color`, format, value))
}

c_format_border_bottom <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_border_bottom`, format, value))
}

c_format_border_bottom_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_border_bottom_color`, format, value))
}

c_format_border_bottom_background_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_border_bottom_background_color`, format, value))
}

c_format_show_border <- function(format) {
    invisible(.Call(`_tabulate_c_format_show_border`, format))
}

c_format_hide_border <- function(format) {
    invisible(.Call(`_tabulate_c_format_hide_border`, format))
}

c_format_show_border_top <- function(format) {
    invisible(.Call(`_tabulate_c_format_show_border_top`, format))
}

c_format_hide_border_top <- function(format) {
    invisible(.Call(`_tabulate_c_format_hide_border_top`, format))
}

c_format_show_border_bottom <- function(format) {
    invisible(.Call(`_tabulate_c_format_show_border_bottom`, format))
}

c_format_hide_border_bottom <- function(format) {
    invisible(.Call(`_tabulate_c_format_hide_border_bottom`, format))
}

c_format_show_border_left <- function(format) {
    invisible(.Call(`_tabulate_c_format_show_border_left`, format))
}

c_format_hide_border_left <- function(format) {
    invisible(.Call(`_tabulate_c_format_hide_border_left`, format))
}

c_format_show_border_right <- function(format) {
    invisible(.Call(`_tabulate_c_format_show_border_right`, format))
}

c_format_hide_border_right <- function(format) {
    invisible(.Call(`_tabulate_c_format_hide_border_right`, format))
}

c_format_corner <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_corner`, format, value))
}

c_format_corner_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_corner_color`, format, value))
}

c_format_corner_background_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_corner_background_color`, format, value))
}

c_format_corner_top_left <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_corner_top_left`, format, value))
}

c_format_corner_top_left_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_corner_top_left_color`, format, value))
}

c_format_corner_top_left_background_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_corner_top_left_background_color`, format, value))
}

c_format_corner_top_right <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_corner_top_right`, format, value))
}

c_format_corner_top_right_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_corner_top_right_color`, format, value))
}

c_format_corner_top_right_background_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_corner_top_right_background_color`, format, value))
}

c_format_corner_bottom_left <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_corner_bottom_left`, format, value))
}

c_format_corner_bottom_left_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_corner_bottom_left_color`, format, value))
}

c_format_corner_bottom_left_background_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_corner_bottom_left_background_color`, format, value))
}

c_format_corner_bottom_right <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_corner_bottom_right`, format, value))
}

c_format_corner_bottom_right_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_corner_bottom_right_color`, format, value))
}

c_format_corner_bottom_right_background_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_corner_bottom_right_background_color`, format, value))
}

c_format_column_separator <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_column_separator`, format, value))
}

c_format_column_separator_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_column_separator_color`, format, value))
}

c_format_column_separator_background_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_column_separator_background_color`, format, value))
}

c_format_font_align <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_font_align`, format, value))
}

c_format_font_style <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_font_style`, format, value))
}

c_format_font_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_font_color`, format, value))
}

c_format_font_background_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_font_background_color`, format, value))
}

c_format_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_color`, format, value))
}

c_format_background_color <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_background_color`, format, value))
}

c_format_multi_byte_characters <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_multi_byte_characters`, format, value))
}

c_format_locale <- function(format, value) {
    invisible(.Call(`_tabulate_c_format_locale`, format, value))
}

row_cell <- function(row, index) {
    .Call(`_tabulate_row_cell`, row, index)
}

row_format <- function(row) {
    .Call(`_tabulate_row_format`, row)
}

#' Create a new tabulate table
#'
#' @param table A table created with [tabulate_table()].
#' @param row A character vector or a tabulate table.
#'
#' @examples
#' table <- tabulate_table() %>%
#'   table_add_row("hello") %>%
#'   table_add_row("world")
#' table
#'
#' @returns
#' A `tabulate_table`.
#'
#' @export
tabulate_table <- function() {
    .Call(`_tabulate_tabulate_table`)
}

#' @describeIn tabulate_table Adds rows to the table.
#' @export
table_add_row <- function(table, row) {
    invisible(.Call(`_tabulate_table_add_row`, table, row))
}

table_column <- function(table, index) {
    .Call(`_tabulate_table_column`, table, index)
}

table_row <- function(table, index) {
    .Call(`_tabulate_table_row`, table, index)
}

table_format <- function(table) {
    .Call(`_tabulate_table_format`, table)
}

tabulate_format <- function(table, colors) {
    .Call(`_tabulate_tabulate_format`, table, colors)
}

