# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tabulate_table <- function() {
    .Call(`_tabulate_tabulate_table`)
}

table_add_row <- function(table, row) {
    invisible(.Call(`_tabulate_table_add_row`, table, row))
}

table_column <- function(table, index) {
    .Call(`_tabulate_table_column`, table, index)
}

column_format <- function(column) {
    .Call(`_tabulate_column_format`, column)
}

column_format_font_align <- function(column, font_align) {
    invisible(.Call(`_tabulate_column_format_font_align`, column, font_align))
}

column_format_font_color <- function(column, color) {
    invisible(.Call(`_tabulate_column_format_font_color`, column, color))
}

tabulate_format <- function(table, colors) {
    .Call(`_tabulate_tabulate_format`, table, colors)
}

