# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tabulate_table <- function() {
    .Call(`_tabulate_tabulate_table`)
}

table_add_row <- function(table, row) {
    invisible(.Call(`_tabulate_table_add_row`, table, row))
}

table_column <- function(table, index) {
    .Call(`_tabulate_table_column`, table, index)
}

tabulate_format <- function(table, colors) {
    .Call(`_tabulate_tabulate_format`, table, colors)
}

column_format <- function(column) {
    .Call(`_tabulate_column_format`, column)
}

column_format_width <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_width`, column, value))
}

column_format_height <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_height`, column, value))
}

column_format_padding <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_padding`, column, value))
}

column_format_padding_left <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_padding_left`, column, value))
}

column_format_padding_right <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_padding_right`, column, value))
}

column_format_padding_top <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_padding_top`, column, value))
}

column_format_padding_bottom <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_padding_bottom`, column, value))
}

column_format_border <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border`, column, value))
}

column_format_border_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_color`, column, value))
}

column_format_border_background_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_background_color`, column, value))
}

column_format_border_left <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_left`, column, value))
}

column_format_border_left_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_left_color`, column, value))
}

column_format_border_left_background_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_left_background_color`, column, value))
}

column_format_border_right <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_right`, column, value))
}

column_format_border_right_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_right_color`, column, value))
}

column_format_border_right_background_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_right_background_color`, column, value))
}

column_format_border_top <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_top`, column, value))
}

column_format_border_top_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_top_color`, column, value))
}

column_format_border_top_background_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_top_background_color`, column, value))
}

column_format_border_bottom <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_bottom`, column, value))
}

column_format_border_bottom_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_bottom_color`, column, value))
}

column_format_border_bottom_background_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_border_bottom_background_color`, column, value))
}

column_format_corner <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_corner`, column, value))
}

column_format_corner_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_corner_color`, column, value))
}

column_format_corner_background_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_corner_background_color`, column, value))
}

column_format_column_separator <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_column_separator`, column, value))
}

column_format_column_separator_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_column_separator_color`, column, value))
}

column_format_column_separator_background_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_column_separator_background_color`, column, value))
}

column_format_font_align <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_font_align`, column, value))
}

column_format_font_style <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_font_style`, column, value))
}

column_format_font_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_font_color`, column, value))
}

column_format_font_background_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_font_background_color`, column, value))
}

column_format_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_color`, column, value))
}

column_format_background_color <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_background_color`, column, value))
}

column_format_multi_byte_characters <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_multi_byte_characters`, column, value))
}

column_format_locale <- function(column, value) {
    invisible(.Call(`_tabulate_column_format_locale`, column, value))
}

